name: SonarCloud Scan

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v2.3.0 
      env:
        SONAR_TOKEN: b9f8dcbd7ae2d97e77ea599cd85e2f8fadc8d267