name: Trivy-Docker

on:
  workflow_call:
    inputs:
      image-ref:
        required: true
        type: string
      format:
        required: false
        default: 'table'
        type: string
      vuln-type:
        required: false
        default: 'os,library'
        type: string
      severity:
        required: false
        default: 'CRITICAL,HIGH,MEDIUM'
        type: string

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build an image from Dockerfile
        run: |
          docker build -t ${{ inputs.image-ref }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.image-ref }}
          format: ${{ inputs.format }}
          vuln-type: ${{ inputs.vuln-type }}
          severity: ${{ inputs.severity }}
